spring:
  #Activiti property configuration
  activiti:
    database-schema-update: true
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    history-level: full
    #表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表，历史表没有建立
    db-history-used: true

  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.254.130:3306/act_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      # 连接只读数据库时配置为true， 保证安全
      readOnly: false
      minimum-idle: 5
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 连接池中允许的最大连接数，缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 10
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      connection-timeout: 30000
      # 测试连接的有效性
      connection-test-query: SELECT 1